In [157]:
import pandas as pd

In [158]:
df_2017 = pd.read_csv('Resources/2017_merged_rushing_salary_finals.csv')
df_2017.head()

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
0,1,Le'Veon Bell,25,PIT,15.0,15.0,321.0,1291.0,9.0,71.0,...,86.1,21.4,3.0,"PB,AP-1",2017,RB,12120000,7.18,2017,pittsburgh-steelers
1,2,LeSean McCoy,29,BUF,16.0,16.0,287.0,1138.0,6.0,57.0,...,71.1,17.9,3.0,PB,2017,RB,10375000,6.21,2017,buffalo-bills
2,3,Melvin Gordon,24,LAC,16.0,16.0,284.0,1105.0,8.0,61.0,...,69.1,17.8,1.0,NaN,2017,RB,2909938,1.72,2017,los-angeles-chargers
3,4,Todd Gurley,23,LAR,15.0,15.0,279.0,1305.0,13.0,69.0,...,87.0,18.6,5.0,"PB,AP-1,AP MVP-2,AP OPoY-1,AP CPoY-6",2017,RB,3769959,2.33,2017,los-angeles-rams
4,5,Jordan Howard,23,CHI,16.0,16.0,276.0,1122.0,9.0,65.0,...,70.1,17.3,1.0,NaN,2017,RB,602005,0.35,2017,chicago-bears

In [159]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 23 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Rk           495 non-null    int64
 1   Player       495 non-null    object
 2   Age          495 non-null    int64
 3   Tm_x         495 non-null    object
 4   G            495 non-null    float64
 5   GS           495 non-null    float64
 6   Att          495 non-null    float64
 7   Yds          495 non-null    float64
 8   TD           495 non-null    float64
 9   1D           495 non-null    float64
 10  Succ%        275 non-null    float64
 11  Lng          263 non-null    float64
 12  Y/A          275 non-null    float64
 13  Y/G          495 non-null    float64
 14  A/G          495 non-null    float64
 15  Fmb          495 non-null    float64
 16  Awards       43 non-null     object
 17  Year_x       495 non-null    int64
 18  Pos          495 non-null    object
 19  Cap Hit      495 non-null    int64
 20  cap_percent  495 non-null    float64
 21  Year_y       495 non-null    int64
 22  Tm_y         495 non-null    object
dtypes: float64(13), int64(5), object(5)
memory usage: 89.1+ KB

In [160]:
df_2018 = pd.read_csv('Resources/2018_merged_rushing_salary_finals.csv')
df_2018.head()

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
0,1,Ezekiel Elliott,23,DAL,15.0,15.0,304.0,1434.0,6.0,74.0,...,95.6,20.3,6.0,"PB,AP-2",2018,RB,6806274,3.68,2018,dallas-cowboys
1,2,Saquon Barkley,21,NYG,16.0,16.0,261.0,1307.0,11.0,50.0,...,81.7,16.3,0.0,"PB,AP ORoY-1",2018,RB,5671773,3.19,2018,new-york-giants
2,3,David Johnson,27,ARI,16.0,16.0,258.0,940.0,7.0,51.0,...,58.8,16.1,3.0,NaN,2018,RB,5042344,2.82,2018,arizona-cardinals
3,4,Todd Gurley,24,LAR,14.0,14.0,256.0,1251.0,17.0,70.0,...,89.4,18.3,1.0,"PB,AP-1,AP OPoY-3",2018,RB,7228306,3.98,2018,los-angeles-rams
4,5,Adrian Peterson,33,WAS,16.0,16.0,251.0,1042.0,7.0,47.0,...,65.1,15.7,3.0,AP CPoY-3,2018,RB,630000,0.35,2018,washington-redskins

In [161]:
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 485 entries, 0 to 484
Data columns (total 23 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Rk           485 non-null    int64
 1   Player       485 non-null    object
 2   Age          485 non-null    int64
 3   Tm_x         485 non-null    object
 4   G            485 non-null    float64
 5   GS           485 non-null    float64
 6   Att          485 non-null    float64
 7   Yds          485 non-null    float64
 8   TD           485 non-null    float64
 9   1D           485 non-null    float64
 10  Succ%        287 non-null    float64
 11  Lng          273 non-null    float64
 12  Y/A          287 non-null    float64
 13  Y/G          485 non-null    float64
 14  A/G          485 non-null    float64
 15  Fmb          485 non-null    float64
 16  Awards       51 non-null     object
 17  Year_x       485 non-null    int64
 18  Pos          485 non-null    object
 19  Cap Hit      485 non-null    int64
 20  cap_percent  485 non-null    float64
 21  Year_y       485 non-null    int64
 22  Tm_y         485 non-null    object
dtypes: float64(13), int64(5), object(5)
memory usage: 87.3+ KB

In [162]:
# concatenating the two dfs
runningback_df = pd.concat([df_2018, df_2017])
runningback_df.head()

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
0,1,Ezekiel Elliott,23,DAL,15.0,15.0,304.0,1434.0,6.0,74.0,...,95.6,20.3,6.0,"PB,AP-2",2018,RB,6806274,3.68,2018,dallas-cowboys
1,2,Saquon Barkley,21,NYG,16.0,16.0,261.0,1307.0,11.0,50.0,...,81.7,16.3,0.0,"PB,AP ORoY-1",2018,RB,5671773,3.19,2018,new-york-giants
2,3,David Johnson,27,ARI,16.0,16.0,258.0,940.0,7.0,51.0,...,58.8,16.1,3.0,NaN,2018,RB,5042344,2.82,2018,arizona-cardinals
3,4,Todd Gurley,24,LAR,14.0,14.0,256.0,1251.0,17.0,70.0,...,89.4,18.3,1.0,"PB,AP-1,AP OPoY-3",2018,RB,7228306,3.98,2018,los-angeles-rams
4,5,Adrian Peterson,33,WAS,16.0,16.0,251.0,1042.0,7.0,47.0,...,65.1,15.7,3.0,AP CPoY-3,2018,RB,630000,0.35,2018,washington-redskins

In [163]:
pd.set_option('display.max_rows', None)

In [164]:
runningback_df['Player'].value_counts()

Player
Deonte Thompson             6
Carlos Hyde                 4
Nick Williams               4
Kapri Bibbs                 4
Brice Butler                4
Brian Hoyer                 4
Dontrelle Inman             4
Golden Tate                 4
Darrell Daniels             4
Amari Cooper                4
Ameer Abdullah              4
Luke Stocker                4
C.J. Anderson               4
Ty Montgomery               3
Michael Thomas              3
Chris Thompson              3
Ryan Griffin                3
Kelvin Benjamin             3
Ross Travis                 3
Hunter Sharp                3
A.J. Derby                  3
Kenny Britt                 3
Kaelin Clay                 3
Andre Ellington             3
Jay Ajayi                   3
Antony Auclair              2
Doug Baldwin                2
Cole Beasley                2
Roosevelt Nix               2
Chester Rogers              2
Eli Rogers                  2
Cameron Brate               2
Antonio Brown               2
Jaron Brown                 2
Noah Brown                  2
Michael Burton              2
Christian McCaffrey         2
Blake Bortles               2
Rex Burkhead                2
Giovani Bernard             2
Jamaal Williams             2
Kenyan Drake                2
Chris Ivory                 2
C.J. Uzomah                 2
Nick Vannett                2
Mike Wallace                2
Joe Webb                    2
Kyle Williams               2
Luke Willson                2
Bobo Wilson                 2
Jeremy Sprinkle             2
Kenny Stills                2
Damien Williams             2
Jameis Winston              2
Kirk Cousins                2
Rod Smith                   2
Jared Goff                  2
Cordarrelle Patterson       2
Javorius Allen              2
Dak Prescott                2
Mitchell Trubisky           2
Russell Wilson              2
Taywan Taylor               2
Trent Taylor                2
Logan Thomas                2
Levine Toilolo              2
Laquon Treadwell            2
Aldrick Robinson            2
Demarcus Robinson           2
Richard Rodgers             2
Kyle Rudolph                2
Ryan Fitzpatrick            2
Devontae Booker             2
Jacquizz Rodgers            2
Matt Ryan                   2
Drew Brees                  2
Ben Roethlisberger          2
DeAndre Washington          2
Jalen Richard               2
Zach Zenner                 2
Wayne Gallman               2
Matthew Stafford            2
Derek Carr                  2
Tom Brady                   2
Tyreek Hill                 2
Brian Hill                  2
Duke Johnson                2
Theo Riddick                2
Ricky Seals-Jones           2
Adam Shaheen                2
Russell Shepard             2
Lee Smith                   2
Torrey Smith                2
David Morgan                2
David Njoku                 2
Nick O'Leary                2
Philip Rivers               2
Tyrod Taylor                2
Eli Manning                 2
Chase Daniel                2
Tyler Lockett               2
Teddy Bridgewater           2
Stevan Ridley               2
Dwayne Washington           2
Case Keenum                 2
James O'Shaughnessy         2
Jamize Olawale              2
DeVante Parker              2
Logan Paulsen               2
Matt LaCosse                2
Stefon Diggs                2
Isaiah McKenzie             2
Keenan Allen                2
Nick Foles                  2
Taylor Gabriel              2
Zach Line                   2
Dede Westbrook              2
Cameron Artis-Payne         2
C.J. Beathard               2
Joe Flacco                  2
Cody Kessler                2
Robert Woods                2
Cody Latimer                2
Marcedes Lewis              2
Josh Malone                 2
Brandon Marshall            2
Vance McDonald              2
Donte Moncrief              2
T.Y. Hilton                 2
Chris Hogan                 2
Austin Hooper               2
Geno Smith                  2
Travis Benjamin             2
Jacoby Brissett             2
Sean Mannion                2
Elijhaa Penny               2
Mohamed Sanu                2
Mike Williams               2
Tavon Austin                2
Corey Davis                 2
Benny Cunningham            2
Brandin Cooks               2
Ryan Switzer                2
DeShone Kizer               2
Chris Moore                 2
Adam Thielen                2
Sammy Watkins               2
Jamison Crowder             2
Brandon Bolden              2
Kyle Juszczyk               2
Brock Osweiler              2
Samaje Perine               2
Todd Gurley                 2
Jesse James                 2
Alshon Jeffery              2
Jermaine Kearse             2
Travis Kelce                2
Lance Kendricks             2
Ryan Grant                  2
Virgil Green                2
Jermaine Gresham            2
Tevin Coleman               2
Jordan Howard               2
Nelson Agholor              2
John Brown                  2
Eric Ebron                  2
Evan Engram                 2
Alex Erickson               2
Ted Ginn Jr.                2
Jarvis Landry               2
James Develin               2
Blaine Gabbert              2
C.J. Ham                    2
DeSean Jackson              2
Sterling Shepard            2
Maxx Williams               2
Derrick Coleman             2
Justin Davis                2
Gerald Everett              2
Marvin Hall                 2
Phillip Dorsett             2
Marquise Goodwin            2
Breshad Perriman            2
Derek Watt                  2
Xavier Grimble              2
Rob Gronkowski              2
Justin Hardy                2
Demetrius Harris            2
Ryan Hewitt                 2
Tyler Higbee                2
Rashard Higgins             2
Josh Hill                   2
Michael Floyd               2
Bennie Fowler               2
Tommylee Lewis              2
Josh Reynolds               2
Andre Roberts               2
Nate Sudfeld                2
Charcandrick West           2
Tyrell Williams             2
J.D. McKissic               2
Seth Roberts                2
Derek Anderson              2
Nick Bellore                2
Tommy Bohanon               2
Trey Burton                 2
Jehu Chesson                2
Corey Coleman               2
Ed Dickson                  2
Patrick DiMarco             2
De'Angelo Henderson         2
Adam Humphries              2
Andy Janovich               2
Julio Jones                 2
Devin Funchess              2
Antonio Gates               2
Shelton Gibson              2
Chris Godwin                2
Jimmy Graham                2
Joe Mixon                   2
Vernon Davis                2
Darrius Heyward-Bey         2
DeAndre Hopkins             2
Zay Jones                   2
George Kittle               2
Jordy Nelson                2
Jarius Wright               2
Brandon Williams            2
Marcus Williams             2
Jamal Agnew                 2
Danny Amendola              2
Seth Devalve                2
Josh Doctson                2
Rhett Ellison               2
Zach Ertz                   2
Mike Evans                  2
Darren Fells                2
Larry Fitzgerald            2
Charles Clay                2
Randall Cobb                2
Keelan Cole                 2
Anthony Sherman             2
Keith Smith                 2
JuJu Smith-Schuster         2
Willie Snead                2
Marlon Mack                 2
Kenny Golladay              2
Chad Henne                  2
Jared Cook                  2
Pharoh Cooper               2
Cody Core                   2
Michael Crabtree            2
Josh Bellamy                2
Mike Davis                  2
Austin Ekeler               2
Chad Williams               2
Davante Adams               2
Peyton Barber               2
LeSean McCoy                2
Dion Lewis                  2
LeGarrette Blount           2
Alfred Blue                 2
Latavius Murray             2
Mark Ingram                 2
Leonard Fournette           2
Alfred Morris               2
Kendrick Bourne             2
Lamar Miller                2
Derrick Henry               2
Melvin Gordon               2
Alvin Kamara                2
T.J. Yeldon                 2
Cam Newton                  2
Tarik Cohen                 2
James White                 2
Elijah McGuire              2
Wendell Smallwood           2
Patrick Mahomes             2
Garrett Celek               2
Chris Jones                 2
Derek Carrier               2
Ezekiel Elliott             2
Nick Boyle                  2
Dwayne Allen                2
Marcus Mariota              2
Doug Martin                 2
Freddie Martino             1
Max McCaffrey               1
Deshaun Watson              1
Josh Allen                  1
Paul Richardson             1
Michael Roberts             1
Travis Rudolph              1
Ty Sambrailo                1
Emmanuel Sanders            1
Tanner McEvoy               1
Sean McGrath                1
Jaydon Mickens              1
Brian Mihalik               1
Louis Murphy                1
Troy Niklas                 1
Greg Olsen                  1
Mark Andrews                1
Dan Arnold                  1
Marcell Ateman              1
Chad Beebe                  1
Blake Bell                  1
Brandon Powell              1
Allen Robinson              1
Ben Braunecker              1
Deontay Burnett             1
Austin Carr                 1
Darren Waller               1
Brandon Weeden              1
Tavon Wilson                1
Lamar Jackson               1
Gus Edwards                 1
Dalvin Cook                 1
Equanimeous St. Brown       1
Courtland Sutton            1
Johnny Townsend             1
Riley Dixon                 1
Jeff Heath                  1
Johnny Hekker               1
Chris Conley                1
River Cracraft              1
Jason Croom                 1
Mason Crosby                1
Dane Cruikshank             1
Sean Culkin                 1
Jerome Cunningham           1
Victor Bolden               1
Jordan Akins                1
Mo Alie-Cox                 1
Taylor Decker               1
Akiem Hicks                 1
Hayden Hurst                1
Melvin Ingram               1
Darius Jennings             1
Kyle Lauletta               1
David Moore                 1
Gehrig Dieter               1
Ross Dwelley                1
George Fant                 1
Anthony Firkser             1
DJ Chark                    1
Tyler Conklin               1
Mark Sanchez                1
Matt Schaub                 1
Tajae Sharpe                1
Marquez Valdes-Scantling    1
Byron Marshall              1
A.J. McCarron               1
Tim Patrick                 1
Cameron Batson              1
Leonte Carroo               1
Michael Dickson             1
Jourdan Lewis               1
Jordan Franks               1
Russell Gage                1
Michael Gallup              1
Rico Gathers                1
Mike Gesicki                1
Dallas Goedert              1
Geremy Davis                1
Dion Dawkins                1
Jonathan Williams           1
Antonio Callaway            1
Matt Cassel                 1
Clayton Fejedelem           1
Dwayne Harris               1
John Ross                   1
Justin Hardee               1
Keon Hatcher                1
Chris Herndon               1
Matt Flanagan               1
Isaiah Ford                 1
Robert Foster               1
T.J. Logan                  1
Ray-Ray McCloud             1
Jeremy McNichols            1
Zach Pascal                 1
Anthony Miller              1
Calvin Ridley               1
Kyle Allen                  1
Josh McCown                 1
Joshua Dobbs                1
Curtis Samuel               1
Richie James                1
Blake Jarwin                1
Andy Jones                  1
Ryan Kelly                  1
Marcus Kemp                 1
Rashad Greene               1
Matt Barkley                1
Keke Coutee                 1
Tre Madden                  1
Darius Jackson              1
Chris Lacy                  1
Alex Armah                  1
Julian Edelman              1
Jeremy Langford             1
Taquan Mizzell              1
Allen Lazard                1
Jordan Leggett              1
Matt Lengel                 1
Chris Manhertz              1
Jordan Matthews             1
Dontrell Hilliard           1
Sam Hubbard                 1
David Williams              1
D'Onta Foreman              1
Travaris Cadet              1
Detrez Newsome              1
Mark Walton                 1
D.J. Moore                  1
Darrel Williams             1
Mike Boone                  1
Darren Sproles              1
John Kelly                  1
Ricky Ortiz                 1
Brian Parker                1
Charone Peake               1
John Phillips               1
MyCole Pruitt               1
Spencer Pulley              1
Damion Ratley               1
Darvin Kidsy                1
Keith Kirkwood              1
Jake Kumerow                1
Jeff Driskel                1
Josh Johnson                1
Ronald Jones II             1
Josh Rosen                  1
Keith Ford                  1
Baker Mayfield              1
Trenton Cannon              1
Dalton Schultz              1
Trent Sherfield             1
Sam Shields                 1
Scott Simonson              1
Vyncint Smith               1
Durham Smythe               1
J'Mon Moore                 1
Johnny Mundt                1
Nick Mullens                1
Andrew Luck                 1
Sam Darnold                 1
Aaron Rodgers               1
Nyheim Hines                1
Rashaad Penny               1
Ian Thomas                  1
Jordan Thomas               1
Jalen Tolliver              1
Malik Turner                1
Eric Saubert                1
Taysom Hill                 1
Kalen Ballage               1
Carson Wentz                1
Ryan Tannehill              1
Spencer Ware                1
Justin Jackson              1
Matt Breida                 1
Mike Gillislee              1
Aaron Jones                 1
Corey Clement               1
Jamaal Charles              1
Alejandro Villanueva        1
James Washington            1
Justin Watson               1
Kevin White                 1
Javon Wims                  1
Le'Veon Bell                1
Kareem Hunt                 1
Frank Gore                  1
Bradley Sowell              1
Joe Staley                  1
Auden Tate                  1
Marshawn Lynch              1
Isaiah Crowell              1
Jonathan Stewart            1
Jeff Wilson                 1
Kenneth Dixon               1
Chase Edmonds               1
Jordan Wilkins              1
Jaylen Samuels              1
Royce Freeman               1
Josh Adams                  1
Devonta Freeman             1
DeMarco Murray              1
Bilal Powell                1
Orleans Darkwa              1
Jerick McKinnon             1
Kerwynn Williams            1
Eddie Lacy                  1
Mike Tolbert                1
Malcolm Brown               1
Alex Smith                  1
Thomas Rawls                1
Shane Vereen                1
Tion Green                  1
Paul Perkins                1
Terrance West               1
Andy Dalton                 1
Brett Hundley               1
Branden Oliver              1
Corey Grant                 1
Terron Ward                 1
Charles Sims                1
Alex Collins                1
Jay Cutler                  1
Kenjon Barner               1
Jimmy Garoppolo             1
Danny Woodhead              1
Lance Dunbar                1
Kevin Hogan                 1
Trey Edmunds                1
Drew Stanton                1
Mack Brown                  1
Landry Jones                1
Senorise Perry              1
Marcus Murphy               1
Nathan Peterman             1
Bryce Petty                 1
ArDarius Stewart            1
Fozzy Whittaker             1
Martavis Bryant             1
D.J. Foster                 1
Michael Campanaro           1
Kellen Clemens              1
MarQueis Gray               1
Adoree' Jackson             1
Matt Jones                  1
Paxton Lynch                1
Aaron Ripkowski             1
T.J. Yates                  1
David Fales                 1
David Fluellen              1
Mike Glennon                1
Ryan Mallett                1
Devante Mays                1
Jakeem Grant                1
Jerell Adams                1
Matt Moore                  1
Albert Wilson               1
Trevor Davis                1
Will Fuller                 1
Marquette King              1
Vince Mayle                 1
Niles Paul                  1
Cooper Rush                 1
C.J. Spiller                1
Lawrence Thomas             1
Scott Tolzien               1
Delanie Walker              1
Terrance Williams           1
Nat Berhe                   1
Tyler Bray                  1
Brandon Coleman             1
Alan Cross                  1
Dez Bryant                  1
Austin Davis                1
Josh Ferguson               1
Taylor Heinicke             1
Bronson Hill                1
Jacob Hollister             1
Marqise Lee                 1
Wil Lutz                    1
Rishard Matthews            1
Braxton Miller              1
Jojo Natson                 1
Kalif Raymond               1
Eric Weems                  1
Jermaine Whitehead          1
Chad Hansen                 1
Maurice Harris              1
Matt Hazel                  1
Kamar Aiken                 1
Geronimo Allison            1
Stephen Anderson            1
Brenton Bersin              1
Tyler Boyd                  1
K.J. Brent                  1
Daniel Brown                1
Marquis Bundy               1
Emanuel Byrd                1
Brent Celek                 1
Orson Charles               1
Michael Clark               1
Sammie Coates               1
Tyler Kroft                 1
Cooper Kupp                 1
Brandon LaFell              1
Roger Lewis                 1
Jeff Cumberland             1
Amara Darboh                1
Eric Decker                 1
Harry Douglas               1
Jack Doyle                  1
Cameron Erving              1
Anthony Fasano              1
Josh Gordon                 1
Hroniss Grasu               1
A.J. Green                  1
Cobi Hamilton               1
James Hanna                 1
Jay Prosch                  1
Brian Quick                 1
Brent Qvale                 1
Patrick Ricard              1
Jeff Heuerman               1
Mack Hollins                1
Gabe Holmes                 1
Johnny Holton               1
Michael Hoomanawanui        1
Justin Hunter               1
Allen Hurns                 1
Jeff Janis                  1
Marcus Johnson              1
Marvin Jones                1
Joe Kerridge                1
Ben Koyack                  1
Kevin Zeitler               1
Nick Chubb                  1
Saquon Barkley              1
David Johnson               1
Adrian Peterson             1
Austin Traylor              1
Leonard Wester              1
Markus Wheaton              1
DeAndrew White              1
Isaac Whitney               1
Marquez Williams            1
Jason Witten                1
Kendall Wright              1
Ricardo Louis               1
Jeremy Maclin               1
Ryan Malleck                1
Demaryius Thomas            1
Mike Thomas                 1
Shaq Thompson               1
Eric Tomlinson              1
Austin Seferian-Jenkins     1
Dion Sims                   1
De'Veon Smith               1
Jonnu Smith                 1
Neal Sterling               1
Phillip Supernaw            1
Geoff Swaim                 1
Brandon Tate                1
Jordan Taylor               1
Randall Telfer              1
Sony Michel                 1
James Conner                1
Name: count, dtype: int64

In [165]:
display(runningback_df[runningback_df['Player'] == 'Deonte Thompson'])
display(runningback_df[runningback_df['Player'] == 'Carlos Hyde'])
display(runningback_df[runningback_df['Player'] == 'Ty Montgomery'])

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
463,565,Deonte Thompson,29,2TM,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,2018,WR,325294,0.17,2018,buffalo-bills
464,565,Deonte Thompson,29,DAL,8.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,2018,WR,325294,0.17,2018,buffalo-bills
465,565,Deonte Thompson,29,BUF,5.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,2018,WR,325294,0.17,2018,buffalo-bills
225,258,Deonte Thompson,28,2TM,16.0,10.0,2.0,-5.0,0.0,0.0,...,-0.3,0.1,1.0,NaN,2017,WR,397471,0.24,2017,buffalo-bills
226,258,Deonte Thompson,28,CHI,5.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,NaN,2017,WR,397471,0.24,2017,buffalo-bills
227,258,Deonte Thompson,28,BUF,11.0,7.0,2.0,-5.0,0.0,0.0,...,-0.5,0.2,0.0,NaN,2017,WR,397471,0.24,2017,buffalo-bills

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
18,22,Carlos Hyde,28,2TM,14.0,7.0,172.0,571.0,5.0,27.0,...,40.8,12.3,2.0,NaN,2018,RB,1245588,0.61,2018,jacksonville-jaguars
19,22,Carlos Hyde,28,CLE,6.0,5.0,114.0,382.0,5.0,20.0,...,63.7,19.0,1.0,NaN,2018,RB,1245588,0.61,2018,jacksonville-jaguars
20,22,Carlos Hyde,28,JAX,8.0,2.0,58.0,189.0,0.0,7.0,...,23.6,7.3,1.0,NaN,2018,RB,1245588,0.61,2018,jacksonville-jaguars
10,11,Carlos Hyde,27,SFO,16.0,16.0,240.0,938.0,8.0,48.0,...,58.6,15.0,2.0,NaN,2017,RB,1171443,0.57,2017,san-francisco-49ers

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
82,96,Ty Montgomery,25,2TM,13.0,0.0,41.0,188.0,1.0,10.0,...,14.5,3.2,2.0,NaN,2018,RB,379323,0.21,2018,baltimore-ravens
83,96,Ty Montgomery,25,GNB,7.0,0.0,26.0,105.0,1.0,6.0,...,15.0,3.7,2.0,NaN,2018,RB,379323,0.21,2018,baltimore-ravens
84,96,Ty Montgomery,25,BAL,6.0,0.0,15.0,83.0,0.0,4.0,...,13.8,2.5,0.0,NaN,2018,RB,379323,0.21,2018,baltimore-ravens

In [166]:
runningback_df.head(10)

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
0,1,Ezekiel Elliott,23,DAL,15.0,15.0,304.0,1434.0,6.0,74.0,...,95.6,20.3,6.0,"PB,AP-2",2018,RB,6806274,3.68,2018,dallas-cowboys
1,2,Saquon Barkley,21,NYG,16.0,16.0,261.0,1307.0,11.0,50.0,...,81.7,16.3,0.0,"PB,AP ORoY-1",2018,RB,5671773,3.19,2018,new-york-giants
2,3,David Johnson,27,ARI,16.0,16.0,258.0,940.0,7.0,51.0,...,58.8,16.1,3.0,NaN,2018,RB,5042344,2.82,2018,arizona-cardinals
3,4,Todd Gurley,24,LAR,14.0,14.0,256.0,1251.0,17.0,70.0,...,89.4,18.3,1.0,"PB,AP-1,AP OPoY-3",2018,RB,7228306,3.98,2018,los-angeles-rams
4,5,Adrian Peterson,33,WAS,16.0,16.0,251.0,1042.0,7.0,47.0,...,65.1,15.7,3.0,AP CPoY-3,2018,RB,630000,0.35,2018,washington-redskins
5,6,Jordan Howard,24,CHI,16.0,15.0,250.0,935.0,9.0,53.0,...,58.4,15.6,2.0,NaN,2018,RB,692005,0.37,2018,chicago-bears
6,8,Joe Mixon,22,CIN,14.0,13.0,237.0,1168.0,8.0,60.0,...,83.4,16.9,0.0,NaN,2018,RB,1238675,0.66,2018,cincinnati-bengals
7,9,Peyton Barber,24,TAM,16.0,16.0,234.0,871.0,5.0,41.0,...,54.4,14.6,1.0,NaN,2018,RB,630000,0.33,2018,tampa-bay-buccaneers
8,10,Christian McCaffrey,22,CAR,16.0,16.0,219.0,1098.0,7.0,53.0,...,68.6,13.7,4.0,AP-2,2018,RB,3918477,2.16,2018,carolina-panthers
9,11,James Conner,23,PIT,13.0,12.0,215.0,973.0,12.0,56.0,...,74.8,16.5,4.0,PB,2018,RB,754572,0.42,2018,pittsburgh-steelers

In [167]:
two_teamers = runningback_df.loc[runningback_df['Tm_x'] == '2TM']['Player']
duplicate_names = runningback_df[runningback_df['Player'].isin(two_teamers)]
duplicate_names_df = duplicate_names

In [168]:
filtered_df = runningback_df[
  runningback_df['Tm_x'].str.contains("TM", na=False) |
  (~runningback_df['Player'].isin(two_teamers))
]
filtered_df['Player'].value_counts()

Player
Michael Thomas              3
Chris Thompson              3
Ryan Griffin                3
Todd Gurley                 2
Marcus Williams             2
Ezekiel Elliott             2
Brandon Williams            2
Chris Jones                 2
Chris Ivory                 2
Kenyan Drake                2
Jamaal Williams             2
Chad Williams               2
Jordan Howard               2
Joe Mixon                   2
Peyton Barber               2
Christian McCaffrey         2
Derrick Henry               2
Lamar Miller                2
Marlon Mack                 2
Alvin Kamara                2
Melvin Gordon               2
Doug Martin                 2
Anthony Sherman             2
Keith Smith                 2
JuJu Smith-Schuster         2
Willie Snead                2
Mark Ingram                 2
Zach Zenner                 2
Wayne Gallman               2
Mike Davis                  2
Alfred Morris               2
Austin Ekeler               2
T.J. Yeldon                 2
Cam Newton                  2
Tarik Cohen                 2
James White                 2
Elijah McGuire              2
Wendell Smallwood           2
Dak Prescott                2
Mitchell Trubisky           2
Russell Wilson              2
Logan Thomas                2
Javorius Allen              2
Duke Johnson                2
Theo Riddick                2
Russell Shepard             2
Lee Smith                   2
Torrey Smith                2
Jeremy Sprinkle             2
Kenny Stills                2
Taywan Taylor               2
Trent Taylor                2
Marcus Mariota              2
Patrick Mahomes             2
Blake Bortles               2
Rex Burkhead                2
Giovani Bernard             2
Jalen Richard               2
Case Keenum                 2
DeVante Parker              2
Logan Paulsen               2
Aldrick Robinson            2
Demarcus Robinson           2
Richard Rodgers             2
Kyle Rudolph                2
Ricky Seals-Jones           2
Adam Shaheen                2
Damien Williams             2
Jameis Winston              2
Kirk Cousins                2
Rod Smith                   2
Jared Goff                  2
Cordarrelle Patterson       2
Vance McDonald              2
Donte Moncrief              2
David Morgan                2
David Njoku                 2
Nick O'Leary                2
James O'Shaughnessy         2
Jamize Olawale              2
Ryan Fitzpatrick            2
Devontae Booker             2
Jacquizz Rodgers            2
Matt Ryan                   2
Drew Brees                  2
Ben Roethlisberger          2
DeAndre Washington          2
Stevan Ridley               2
Dwayne Washington           2
Benny Cunningham            2
Brandin Cooks               2
Stefon Diggs                2
Matthew Stafford            2
Derek Carr                  2
Tom Brady                   2
Tyreek Hill                 2
Brian Hill                  2
Cameron Artis-Payne         2
C.J. Beathard               2
Joe Flacco                  2
Cody Kessler                2
Robert Woods                2
Marcedes Lewis              2
Josh Malone                 2
Brandon Marshall            2
Kyle Juszczyk               2
Brock Osweiler              2
Samaje Perine               2
Geno Smith                  2
Alshon Jeffery              2
Jermaine Kearse             2
Travis Kelce                2
Lance Kendricks             2
Matt LaCosse                2
Cody Latimer                2
Philip Rivers               2
Tyrod Taylor                2
Eli Manning                 2
Chase Daniel                2
Tyler Lockett               2
Teddy Bridgewater           2
Demetrius Harris            2
Ryan Hewitt                 2
Tyler Higbee                2
Rashard Higgins             2
Josh Hill                   2
T.Y. Hilton                 2
Chris Hogan                 2
Austin Hooper               2
Jesse James                 2
Isaiah McKenzie             2
Keenan Allen                2
Nick Foles                  2
Taylor Gabriel              2
Zach Line                   2
Dede Westbrook              2
Brandon Bolden              2
Marquise Goodwin            2
Breshad Perriman            2
Derek Watt                  2
Travis Benjamin             2
Jacoby Brissett             2
Sean Mannion                2
Elijhaa Penny               2
Mohamed Sanu                2
Mike Williams               2
Tavon Austin                2
Corey Davis                 2
James Develin               2
Blaine Gabbert              2
C.J. Ham                    2
DeSean Jackson              2
Justin Hardy                2
Shelton Gibson              2
Chris Godwin                2
Jimmy Graham                2
Ryan Grant                  2
Virgil Green                2
Jermaine Gresham            2
Latavius Murray             2
Xavier Grimble              2
Rob Gronkowski              2
Ryan Switzer                2
DeShone Kizer               2
Chris Moore                 2
Adam Thielen                2
Sammy Watkins               2
Jamison Crowder             2
Phillip Dorsett             2
De'Angelo Henderson         2
Adam Humphries              2
Andy Janovich               2
Julio Jones                 2
Tommylee Lewis              2
Nelson Agholor              2
John Brown                  2
Eric Ebron                  2
Evan Engram                 2
Alex Erickson               2
Ted Ginn Jr.                2
Jarvis Landry               2
J.D. McKissic               2
Seth Roberts                2
Sterling Shepard            2
Antonio Gates               2
Danny Amendola              2
Derek Anderson              2
Josh Doctson                2
Rhett Ellison               2
Zach Ertz                   2
Mike Evans                  2
Darren Fells                2
Larry Fitzgerald            2
Michael Floyd               2
Bennie Fowler               2
Devin Funchess              2
Maxx Williams               2
Derrick Coleman             2
Justin Davis                2
Gerald Everett              2
Marvin Hall                 2
Patrick DiMarco             2
Kenny Golladay              2
Chad Henne                  2
Darrius Heyward-Bey         2
Pharoh Cooper               2
Cody Core                   2
Michael Crabtree            2
Vernon Davis                2
Seth Devalve                2
Josh Reynolds               2
Andre Roberts               2
Nate Sudfeld                2
Charcandrick West           2
Tyrell Williams             2
Jarius Wright               2
Jamal Agnew                 2
Antonio Brown               2
Jaron Brown                 2
Noah Brown                  2
Michael Burton              2
Derek Carrier               2
Garrett Celek               2
Charles Clay                2
Randall Cobb                2
Keelan Cole                 2
Jared Cook                  2
Nick Bellore                2
Tommy Bohanon               2
Trey Burton                 2
Jehu Chesson                2
Corey Coleman               2
Ed Dickson                  2
Leonard Fournette           2
Levine Toilolo              2
Laquon Treadwell            2
C.J. Uzomah                 2
Nick Vannett                2
Mike Wallace                2
Joe Webb                    2
Kyle Williams               2
Luke Willson                2
Bobo Wilson                 2
Tevin Coleman               2
LeSean McCoy                2
Dion Lewis                  2
LeGarrette Blount           2
Alfred Blue                 2
Deonte Thompson             2
Eli Rogers                  2
Dwayne Allen                2
Antony Auclair              2
Doug Baldwin                2
Cole Beasley                2
Josh Bellamy                2
Kendrick Bourne             2
Nick Boyle                  2
Cameron Brate               2
DeAndre Hopkins             2
Zay Jones                   2
George Kittle               2
Jordy Nelson                2
Roosevelt Nix               2
Chester Rogers              2
Davante Adams               2
Kevin Zeitler               1
Adrian Peterson             1
James Conner                1
Sony Michel                 1
Nick Chubb                  1
Paul Richardson             1
Patrick Ricard              1
Brent Qvale                 1
Brian Quick                 1
Jay Prosch                  1
Greg Olsen                  1
Troy Niklas                 1
Louis Murphy                1
Brian Mihalik               1
Jaydon Mickens              1
Sean McGrath                1
Tanner McEvoy               1
Max McCaffrey               1
Freddie Martino             1
Ryan Malleck                1
Jeremy Maclin               1
Kelvin Benjamin             1
Blake Bell                  1
Chad Beebe                  1
Marcell Ateman              1
Dan Arnold                  1
Mark Andrews                1
Mo Alie-Cox                 1
Jordan Akins                1
Tavon Wilson                1
Brandon Weeden              1
Darren Waller               1
Johnny Townsend             1
Courtland Sutton            1
Equanimeous St. Brown       1
Tajae Sharpe                1
Matt Schaub                 1
Tyler Conklin               1
DJ Chark                    1
Austin Carr                 1
Brice Butler                1
Deontay Burnett             1
Mark Sanchez                1
Allen Robinson              1
Brandon Powell              1
David Moore                 1
Kyle Lauletta               1
Darius Jennings             1
Melvin Ingram               1
Hayden Hurst                1
Akiem Hicks                 1
Ben Braunecker              1
Victor Bolden               1
Dion Dawkins                1
Geremy Davis                1
Darrell Daniels             1
Jerome Cunningham           1
Sean Culkin                 1
Dane Cruikshank             1
Mason Crosby                1
Jason Croom                 1
River Cracraft              1
Johnny Hekker               1
Jeff Heath                  1
Riley Dixon                 1
Michael Dickson             1
Leonte Carroo               1
Cameron Batson              1
Chris Conley                1
Jordan Franks               1
Robert Foster               1
Isaiah Ford                 1
Matt Flanagan               1
Anthony Firkser             1
George Fant                 1
Ross Dwelley                1
Ameer Abdullah              1
Amari Cooper                1
Marquez Valdes-Scantling    1
Zach Pascal                 1
Jeremy McNichols            1
Ray-Ray McCloud             1
T.J. Logan                  1
Gehrig Dieter               1
Taylor Decker               1
Mike Gesicki                1
Rico Gathers                1
Michael Gallup              1
Russell Gage                1
Tim Patrick                 1
A.J. McCarron               1
Byron Marshall              1
Tre Madden                  1
Keke Coutee                 1
Matt Barkley                1
Jourdan Lewis               1
Dwayne Harris               1
Clayton Fejedelem           1
Matt Cassel                 1
Antonio Callaway            1
Jonathan Williams           1
Dontrell Hilliard           1
Chris Herndon               1
Keon Hatcher                1
Justin Hardee               1
Anthony Miller              1
Darius Jackson              1
D'Onta Foreman              1
David Williams              1
Golden Tate                 1
John Ross                   1
Joshua Dobbs                1
Josh McCown                 1
Kyle Allen                  1
Calvin Ridley               1
Rashad Greene               1
Dallas Goedert              1
Allen Lazard                1
Chris Lacy                  1
Jake Kumerow                1
Keith Kirkwood              1
Darvin Kidsy                1
Marcus Kemp                 1
Ryan Kelly                  1
Andy Jones                  1
Blake Jarwin                1
Curtis Samuel               1
Taquan Mizzell              1
Jeremy Langford             1
Julian Edelman              1
Alex Armah                  1
Richie James                1
Sam Hubbard                 1
Chris Manhertz              1
Matt Lengel                 1
Kapri Bibbs                 1
Keith Ford                  1
Josh Rosen                  1
Ronald Jones II             1
Josh Johnson                1
Jeff Driskel                1
Detrez Newsome              1
Travaris Cadet              1
Mike Boone                  1
Darrel Williams             1
D.J. Moore                  1
Mark Walton                 1
Nick Mullens                1
Jordan Leggett              1
Damion Ratley               1
Spencer Pulley              1
MyCole Pruitt               1
John Phillips               1
Charone Peake               1
Brian Parker                1
John Kelly                  1
Darren Sproles              1
Ryan Tannehill              1
Carson Wentz                1
Kalen Ballage               1
Taysom Hill                 1
Ricky Ortiz                 1
Johnny Mundt                1
J'Mon Moore                 1
Jordan Matthews             1
Auden Tate                  1
Joe Staley                  1
Bradley Sowell              1
Durham Smythe               1
Vyncint Smith               1
Scott Simonson              1
Sam Shields                 1
Trent Sherfield             1
Trenton Cannon              1
Baker Mayfield              1
Ty Montgomery               1
Aaron Rodgers               1
Sam Darnold                 1
Andrew Luck                 1
Dalton Schultz              1
Eric Saubert                1
Malik Turner                1
Jalen Tolliver              1
Jordan Thomas               1
Rashaad Penny               1
Nyheim Hines                1
Josh Allen                  1
Deshaun Watson              1
Justin Jackson              1
Spencer Ware                1
Jaylen Samuels              1
Jordan Wilkins              1
Chase Edmonds               1
Kenneth Dixon               1
Jeff Wilson                 1
C.J. Anderson               1
Ian Thomas                  1
DeMarco Murray              1
Devonta Freeman             1
Jonathan Stewart            1
Isaiah Crowell              1
Marshawn Lynch              1
Jay Ajayi                   1
Alex Collins                1
Frank Gore                  1
Kareem Hunt                 1
Le'Veon Bell                1
Javon Wims                  1
Nick Williams               1
Kevin White                 1
Justin Watson               1
James Washington            1
Alejandro Villanueva        1
Tion Green                  1
Shane Vereen                1
Thomas Rawls                1
Alex Smith                  1
Malcolm Brown               1
Mike Tolbert                1
Eddie Lacy                  1
Jamaal Charles              1
Corey Clement               1
Aaron Jones                 1
Mike Gillislee              1
Matt Breida                 1
Kerwynn Williams            1
Jerick McKinnon             1
Orleans Darkwa              1
Bilal Powell                1
Trey Edmunds                1
Kevin Hogan                 1
Lance Dunbar                1
Danny Woodhead              1
Jimmy Garoppolo             1
Kenjon Barner               1
Jay Cutler                  1
Andre Ellington             1
Charles Sims                1
Terron Ward                 1
Corey Grant                 1
Branden Oliver              1
Brett Hundley               1
Andy Dalton                 1
Terrance West               1
Paul Perkins                1
Adoree' Jackson             1
MarQueis Gray               1
Kellen Clemens              1
Michael Campanaro           1
D.J. Foster                 1
Martavis Bryant             1
Fozzy Whittaker             1
ArDarius Stewart            1
Bryce Petty                 1
Nathan Peterman             1
Marcus Murphy               1
Senorise Perry              1
Landry Jones                1
Mack Brown                  1
Brian Hoyer                 1
Drew Stanton                1
Marquette King              1
Will Fuller                 1
Trevor Davis                1
Kaelin Clay                 1
Albert Wilson               1
Matt Moore                  1
Jakeem Grant                1
Devante Mays                1
Ryan Mallett                1
Mike Glennon                1
David Fluellen              1
David Fales                 1
T.J. Yates                  1
Aaron Ripkowski             1
Paxton Lynch                1
Matt Jones                  1
Dez Bryant                  1
Tyler Bray                  1
Nat Berhe                   1
Terrance Williams           1
Delanie Walker              1
Scott Tolzien               1
Lawrence Thomas             1
C.J. Spiller                1
Cooper Rush                 1
Niles Paul                  1
Josh Adams                  1
Royce Freeman               1
Dalvin Cook                 1
Gus Edwards                 1
Lamar Jackson               1
Vince Mayle                 1
Geronimo Allison            1
Kamar Aiken                 1
Jerell Adams                1
Jermaine Whitehead          1
Eric Weems                  1
Kalif Raymond               1
Jojo Natson                 1
Braxton Miller              1
Rishard Matthews            1
Wil Lutz                    1
Marqise Lee                 1
Jacob Hollister             1
Bronson Hill                1
Taylor Heinicke             1
Josh Ferguson               1
Austin Davis                1
Amara Darboh                1
Jeff Cumberland             1
Alan Cross                  1
Brandon Coleman             1
Sammie Coates               1
Michael Clark               1
Orson Charles               1
Brent Celek                 1
Emanuel Byrd                1
Marquis Bundy               1
Daniel Brown                1
Kenny Britt                 1
K.J. Brent                  1
Tyler Boyd                  1
Brenton Bersin              1
Stephen Anderson            1
Mack Hollins                1
Jeff Heuerman               1
Matt Hazel                  1
Maurice Harris              1
Chad Hansen                 1
James Hanna                 1
Cobi Hamilton               1
A.J. Green                  1
Hroniss Grasu               1
Josh Gordon                 1
Anthony Fasano              1
Cameron Erving              1
Jack Doyle                  1
Harry Douglas               1
A.J. Derby                  1
Eric Decker                 1
Ricardo Louis               1
Roger Lewis                 1
Brandon LaFell              1
Cooper Kupp                 1
Tyler Kroft                 1
Ben Koyack                  1
Joe Kerridge                1
Marvin Jones                1
Marcus Johnson              1
Jeff Janis                  1
Dontrelle Inman             1
Allen Hurns                 1
Justin Hunter               1
Michael Hoomanawanui        1
Johnny Holton               1
Gabe Holmes                 1
Carlos Hyde                 1
Kendall Wright              1
Jason Witten                1
Marquez Williams            1
Saquon Barkley              1
David Johnson               1
Isaac Whitney               1
DeAndrew White              1
Markus Wheaton              1
Leonard Wester              1
Austin Traylor              1
Austin Seferian-Jenkins     1
Emmanuel Sanders            1
Ty Sambrailo                1
Travis Rudolph              1
Michael Roberts             1
Ross Travis                 1
Eric Tomlinson              1
Shaq Thompson               1
Mike Thomas                 1
Demaryius Thomas            1
Randall Telfer              1
Jordan Taylor               1
Brandon Tate                1
Geoff Swaim                 1
Phillip Supernaw            1
Luke Stocker                1
Neal Sterling               1
Jonnu Smith                 1
De'Veon Smith               1
Dion Sims                   1
Hunter Sharp                1
Name: count, dtype: int64

In [169]:
display(filtered_df[filtered_df['Player'] == 'Michael Thomas'])
display(runningback_df[runningback_df['Player'] == 'Michael Thomas'])
display(runningback_df[runningback_df['Player'] == 'Chris Thompson'])
display(runningback_df[runningback_df['Player'] == 'Ryan Griffin'])

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
461,564,Michael Thomas,25,NOR,16.0,16.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,"PB,AP-1",2018,WR,1396083,0.79,2018,new-orleans-saints
462,564,Michael Thomas,25,NOR,16.0,16.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,"PB,AP-1",2018,FS,2000000,1.13,2018,new-york-giants
463,533,Michael Thomas,24,NOR,16.0,14.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,PB,2017,WR,1163403,0.71,2017,new-orleans-saints

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
461,564,Michael Thomas,25,NOR,16.0,16.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,"PB,AP-1",2018,WR,1396083,0.79,2018,new-orleans-saints
462,564,Michael Thomas,25,NOR,16.0,16.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,"PB,AP-1",2018,FS,2000000,1.13,2018,new-york-giants
463,533,Michael Thomas,24,NOR,16.0,14.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,PB,2017,WR,1163403,0.71,2017,new-orleans-saints

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
79,92,Chris Thompson,28,WAS,10.0,0.0,43.0,178.0,0.0,9.0,...,17.8,4.3,1.0,NaN,2018,RB,3152250,1.76,2018,washington-redskins
66,70,Chris Thompson,27,WAS,10.0,1.0,64.0,294.0,2.0,11.0,...,29.4,6.4,3.0,NaN,2017,WR,382942,0.22,2017,houston-texans
465,535,Chris Thompson,23,HOU,13.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,NaN,2017,WR,382942,0.22,2017,houston-texans

,Rk,Player,Age,Tm_x,G,GS,Att,Yds,TD,1D,...,Y/G,A/G,Fmb,Awards,Year_x,Pos,Cap Hit,cap_percent,Year_y,Tm_y
374,440,Ryan Griffin,28,HOU,14.0,11.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,2018,QB,1393750,0.72,2018,tampa-bay-buccaneers
375,440,Ryan Griffin,28,HOU,14.0,11.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,2018,TE,2687500,1.44,2018,houston-texans
353,406,Ryan Griffin,27,HOU,7.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,2017,QB,1150000,0.67,2017,tampa-bay-buccaneers

In [170]:
# dropping oddball name duplicates
filtered_df = filtered_df.drop(index=[375, 465, 462])

In [171]:
filtered_df = filtered_df.drop(columns=['Year_y', 'Tm_y'])
filtered_df = filtered_df.rename(columns={'Tm_x': 'Tm', 'Year_x': 'Year'})
filtered_df.head(10)

,Rk,Player,Age,Tm,G,GS,Att,Yds,TD,1D,...,Lng,Y/A,Y/G,A/G,Fmb,Awards,Year,Pos,Cap Hit,cap_percent
0,1,Ezekiel Elliott,23,DAL,15.0,15.0,304.0,1434.0,6.0,74.0,...,41.0,4.7,95.6,20.3,6.0,"PB,AP-2",2018,RB,6806274,3.68
1,2,Saquon Barkley,21,NYG,16.0,16.0,261.0,1307.0,11.0,50.0,...,78.0,5.0,81.7,16.3,0.0,"PB,AP ORoY-1",2018,RB,5671773,3.19
2,3,David Johnson,27,ARI,16.0,16.0,258.0,940.0,7.0,51.0,...,53.0,3.6,58.8,16.1,3.0,NaN,2018,RB,5042344,2.82
3,4,Todd Gurley,24,LAR,14.0,14.0,256.0,1251.0,17.0,70.0,...,36.0,4.9,89.4,18.3,1.0,"PB,AP-1,AP OPoY-3",2018,RB,7228306,3.98
4,5,Adrian Peterson,33,WAS,16.0,16.0,251.0,1042.0,7.0,47.0,...,90.0,4.2,65.1,15.7,3.0,AP CPoY-3,2018,RB,630000,0.35
5,6,Jordan Howard,24,CHI,16.0,15.0,250.0,935.0,9.0,53.0,...,42.0,3.7,58.4,15.6,2.0,NaN,2018,RB,692005,0.37
6,8,Joe Mixon,22,CIN,14.0,13.0,237.0,1168.0,8.0,60.0,...,51.0,4.9,83.4,16.9,0.0,NaN,2018,RB,1238675,0.66
7,9,Peyton Barber,24,TAM,16.0,16.0,234.0,871.0,5.0,41.0,...,28.0,3.7,54.4,14.6,1.0,NaN,2018,RB,630000,0.33
8,10,Christian McCaffrey,22,CAR,16.0,16.0,219.0,1098.0,7.0,53.0,...,59.0,5.0,68.6,13.7,4.0,AP-2,2018,RB,3918477,2.16
9,11,James Conner,23,PIT,13.0,12.0,215.0,973.0,12.0,56.0,...,30.0,4.5,74.8,16.5,4.0,PB,2018,RB,754572,0.42

In [172]:
filtered_df.columns

Index(['Rk', 'Player', 'Age', 'Tm', 'G', 'GS', 'Att', 'Yds', 'TD', '1D',
       'Succ%', 'Lng', 'Y/A', 'Y/G', 'A/G', 'Fmb', 'Awards', 'Year', 'Pos',
       'Cap Hit', 'cap_percent'],
      dtype='object')

In [173]:
filtered_df = filtered_df.rename(columns={
    'Rk': 'Rank', 'Tm': 'Team', 'G': 'Games Played', 'GS': 'Games Started',
    'Att': 'Attempts', 'Yds': 'Yards', 'TD': 'Touchdowns', '1D': ' First Downs',
    'Succ%': 'Success Percentage', 'Lng': 'Longest Run', 'Y/A': 'Yards per Attempt',
    'Y/G': 'Yards per Game', 'A/G': 'Attempts per Game', 'Fmb': 'Fumbles', 'Pos': 'Position',
    'cap_percent': 'Cap%'})

In [174]:
filtered_df.head()

,Rank,Player,Age,Team,Games Played,Games Started,Attempts,Yards,Touchdowns,First Downs,...,Longest Run,Yards per Attempt,Yards per Game,Attempts per Game,Fumbles,Awards,Year,Position,Cap Hit,Cap%
0,1,Ezekiel Elliott,23,DAL,15.0,15.0,304.0,1434.0,6.0,74.0,...,41.0,4.7,95.6,20.3,6.0,"PB,AP-2",2018,RB,6806274,3.68
1,2,Saquon Barkley,21,NYG,16.0,16.0,261.0,1307.0,11.0,50.0,...,78.0,5.0,81.7,16.3,0.0,"PB,AP ORoY-1",2018,RB,5671773,3.19
2,3,David Johnson,27,ARI,16.0,16.0,258.0,940.0,7.0,51.0,...,53.0,3.6,58.8,16.1,3.0,NaN,2018,RB,5042344,2.82
3,4,Todd Gurley,24,LAR,14.0,14.0,256.0,1251.0,17.0,70.0,...,36.0,4.9,89.4,18.3,1.0,"PB,AP-1,AP OPoY-3",2018,RB,7228306,3.98
4,5,Adrian Peterson,33,WAS,16.0,16.0,251.0,1042.0,7.0,47.0,...,90.0,4.2,65.1,15.7,3.0,AP CPoY-3,2018,RB,630000,0.35

In [175]:
# adding awards as individual columns
# PB: Proball
# AP: All Pro 
# OroY: Offensive rookie of the year
# OPoY: Offensive Player of the year
# CPoY: Comeback player of the year

filtered_df['Awards'] = filtered_df.apply(lambda x: str(x['Awards']).replace(' ', ','), axis=1)

# getting a list of all possible awards given
awards = filtered_df.loc[filtered_df['Awards'].notna()]['Awards']
possible_awards = []
for award_list in awards:
    award_given_list = award_list.split(sep=',')
    for award_given in award_given_list:
        if '-' in award_given:
            award_given = award_given.split(sep='-')[0]
            award_given = award_given.strip()
        if award_given not in possible_awards:
            possible_awards.append(award_given)

possible_awards

['PB', 'AP', 'ORoY', 'nan', 'OPoY', 'CPoY', 'MVP']

In [176]:
# applying award ammounts
def get_award_count(row, award_name):
    # Catch Empty
    if row['Awards'] is None:
        return 0

    # Check for specific award
    index = row['Awards'].find(award_name)
    if index >= 0:
        # getting section containing named award at the beginning
        award = row['Awards'][index:]

        # removing multiple entries after award if they exist
        if ',' in award:
            award = award.split(sep=',')[0]

        # if multiple times awarded, get the amount
        if '-' in award:
            return int(award.split(sep='-')[1])
        else:
            return 1
        
    # if no awards by that name, return 0
    else:
        return 0
    
possible_awards.remove('nan')
possible_awards

['PB', 'AP', 'ORoY', 'OPoY', 'CPoY', 'MVP']

In [177]:
# testing to make sure it works
display(filtered_df.iloc[0, :])
display(get_award_count(filtered_df.iloc[0, :], 'AP'))
display(get_award_count(filtered_df.iloc[0, :], 'PB'))

Rank                                1
Player                Ezekiel Elliott
Age                                23
Team                              DAL
Games Played                     15.0
Games Started                    15.0
Attempts                        304.0
Yards                          1434.0
Touchdowns                        6.0
 First Downs                     74.0
Success Percentage               49.0
Longest Run                      41.0
Yards per Attempt                 4.7
Yards per Game                   95.6
Attempts per Game                20.3
Fumbles                           6.0
Awards                        PB,AP-2
Year                             2018
Position                           RB
Cap Hit                       6806274
Cap%                             3.68
Name: 0, dtype: object

2

1

In [178]:
# adding in new awards
for award in possible_awards:
    filtered_df[award] = filtered_df.apply(lambda row: get_award_count(row, award), axis=1)

# checking for correct entry
filtered_df.head()

,Rank,Player,Age,Team,Games Played,Games Started,Attempts,Yards,Touchdowns,First Downs,...,Year,Position,Cap Hit,Cap%,PB,AP,ORoY,OPoY,CPoY,MVP
0,1,Ezekiel Elliott,23,DAL,15.0,15.0,304.0,1434.0,6.0,74.0,...,2018,RB,6806274,3.68,1,2,0,0,0,0
1,2,Saquon Barkley,21,NYG,16.0,16.0,261.0,1307.0,11.0,50.0,...,2018,RB,5671773,3.19,1,1,1,0,0,0
2,3,David Johnson,27,ARI,16.0,16.0,258.0,940.0,7.0,51.0,...,2018,RB,5042344,2.82,0,0,0,0,0,0
3,4,Todd Gurley,24,LAR,14.0,14.0,256.0,1251.0,17.0,70.0,...,2018,RB,7228306,3.98,1,1,0,3,0,0
4,5,Adrian Peterson,33,WAS,16.0,16.0,251.0,1042.0,7.0,47.0,...,2018,RB,630000,0.35,0,1,0,0,3,0

In [179]:
# calculating total awards
def total_rows(row):
    total = 0
    for award in possible_awards:
        total += row[award]
    return total

filtered_df['Total Awards'] = filtered_df.apply(lambda row: total_rows(row), axis=1)

In [ ]:
# dropping the original awards column
filtered_df = filtered_df.drop(columns='Awards')

filtered_df.head(10)

,Rank,Player,Age,Team,Games Played,Games Started,Attempts,Yards,Touchdowns,First Downs,...,Position,Cap Hit,Cap%,PB,AP,ORoY,OPoY,CPoY,MVP,Total Awards
0,1,Ezekiel Elliott,23,DAL,15.0,15.0,304.0,1434.0,6.0,74.0,...,RB,6806274,3.68,1,2,0,0,0,0,3
1,2,Saquon Barkley,21,NYG,16.0,16.0,261.0,1307.0,11.0,50.0,...,RB,5671773,3.19,1,1,1,0,0,0,3
2,3,David Johnson,27,ARI,16.0,16.0,258.0,940.0,7.0,51.0,...,RB,5042344,2.82,0,0,0,0,0,0,0
3,4,Todd Gurley,24,LAR,14.0,14.0,256.0,1251.0,17.0,70.0,...,RB,7228306,3.98,1,1,0,3,0,0,5
4,5,Adrian Peterson,33,WAS,16.0,16.0,251.0,1042.0,7.0,47.0,...,RB,630000,0.35,0,1,0,0,3,0,4
5,6,Jordan Howard,24,CHI,16.0,15.0,250.0,935.0,9.0,53.0,...,RB,692005,0.37,0,0,0,0,0,0,0
6,8,Joe Mixon,22,CIN,14.0,13.0,237.0,1168.0,8.0,60.0,...,RB,1238675,0.66,0,0,0,0,0,0,0
7,9,Peyton Barber,24,TAM,16.0,16.0,234.0,871.0,5.0,41.0,...,RB,630000,0.33,0,0,0,0,0,0,0
8,10,Christian McCaffrey,22,CAR,16.0,16.0,219.0,1098.0,7.0,53.0,...,RB,3918477,2.16,0,2,0,0,0,0,2
9,11,James Conner,23,PIT,13.0,12.0,215.0,973.0,12.0,56.0,...,RB,754572,0.42,1,0,0,0,0,0,1

In [182]:
filtered_df.to_csv('Runningback Salary Cap 2017-2018 w Awards.csv')